services:
  anypost-db:
    image: postgres:13-alpine
    container_name: anypost-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}


volumes:
  postgres-data: